# Шаблоны для поиска stencil объектов в файлах drawio
---
Segnent:
  patterns:
    - 'fillColor=#BFBFBF|value="INET-EDGE"'
  parsers:
    - description: "value=\"([^\"]+)\""
  schema: "none"

Network:
  patterns:
    - "fillColor=#c0cfe2;shape=stencil(;rounded=1"
  parsers:
    - {"ip": "(\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\s*(?:/\\s*\\d{1,2}|/\\s*(?:255|254|252|248|240|224|192|128)\\.(?:255|254|252|248|240|224|192|128|0)\\.(?:255|254|252|248|240|224|192|128|0)\\.(?:255|254|252|248|240|224|192|128|0))?\\b)"}
    - {"description": ".*"}
  schema: "none"

Router:
  patterns:
    - "shape=mxgraph.cisco.routers.router;html=1;pointerEvents=1;dashed=0;fillColor=#036897;strokeColor=#ffffff;strokeWidth=2;verticalLabelPosition=bottom;verticalAlign=top;align=center;outlineConnect=0;labelBackgroundColor=default;fontSize=12;fontColor=#FFFFFF"
  parsers:
    - description: ".*"
  schema: "none"

Switch:
  patterns:
    - "shape=mxgraph.cisco.wireless.wlan_controller;"
    - "shape=mxgraph.cisco.switches.workgroup_switch;"
  parsers:
    - description: ".*"
  schema: "none"